// Language translations for Asisten Officer

export type Language = 'id' | 'en' | 'zh';

export interface Translations {
  [key: string]: string;
}

export const translations: Record<Language, Translations> = {
  id: {
    // Menu items
    'menu.home': 'Beranda',
    'menu.magvar': 'Variasi Magnetik',
    'menu.cpa': 'CPA / TCPA',
    'menu.eta': 'Kalkulator ETA',
    'menu.wind': 'Kalkulator Angin',
    'menu.sextant': 'Sekstan',
    'menu.colreg': 'COLREG',
    'menu.draft': 'Draft Survey',
    'menu.paint': 'Kalkulator Cat',
    'menu.azimuth': 'Azimut Matahari',
    'menu.compass': 'Kalibrasi Kompas',
    'menu.star': 'Pencari Bintang',
    'menu.logbook': 'Referensi Logbook',
    
    // Common
    'common.calculate': 'HITUNG',
    'common.clear': 'BERSIHKAN',
    'common.save': 'SIMPAN',
    'common.cancel': 'BATAL',
    'common.close': 'TUTUP',
    'common.about': 'Tentang',
    'common.settings': 'Pengaturan',
    'common.language': 'Bahasa',
    'common.export': 'EXPORT',
    'common.history': 'Riwayat',
    'common.degrees': 'derajat',
    'common.minutes': 'menit',
    'common.knots': 'knot',
    'common.nm': 'NM',
    'common.meters': 'm',
    'common.tons': 'MT',
    
    // Home
    'home.title': 'MARINE NAVIGATION',
    'home.subtitle': 'Integrated Officer Assistance Toolkit',
    'home.version': 'Versi',
    
    // Magnetic Variation
    'magvar.title': 'Variasi Magnetik',
    'magvar.subtitle': 'WMM2025 - NOAA Compliant',
    'magvar.latitude': 'Lintang',
    'magvar.longitude': 'Bujur',
    'magvar.dateTime': 'Tanggal & Waktu',
    'magvar.getPosition': 'Ambil Posisi GPS',
    'magvar.setNow': 'Atur ke Sekarang',
    'magvar.headingConversion': 'Konversi Heading',
    'magvar.trueToCompass': 'True → Compass',
    'magvar.compassToTrue': 'Compass → True',
    'magvar.trueHeading': 'True Heading',
    'magvar.compassHeading': 'Compass Heading',
    'magvar.result': 'Variasi Magnetik',
    'magvar.annualChange': 'Perubahan Tahunan',
    'magvar.compassError': 'Error Kompas',
    'magvar.epoch': 'Epoch WMM2025',
    'magvar.calculatedHeading': 'Heading Terkonversi',
    
    // CPA/TCPA
    'cpa.title': 'CPA / TCPA',
    'cpa.subtitle': 'Closest Point of Approach',
    'cpa.ownVessel': 'Kapal Sendiri',
    'cpa.targetVessel': 'Kapal Target',
    'cpa.range': 'Jarak',
    'cpa.bearing': 'Bearing',
    'cpa.course': 'Course',
    'cpa.speed': 'Speed',
    'cpa.cpa': 'CPA',
    'cpa.tcpa': 'TCPA',
    'cpa.status': 'Status',
    'cpa.safe': 'AMAN',
    'cpa.caution': 'WASPADA',
    'cpa.danger': 'BAHAYA',
    'cpa.passed': 'LEWAT',
    'cpa.cpaDistance': 'Jarak CPA',
    'cpa.tcpaTime': 'Waktu ke CPA',
    'cpa.cpaBearing': 'Bearing CPA',
    
    // ETA
    'eta.title': 'Kalkulator ETA',
    'eta.subtitle': 'Estimated Time of Arrival',
    'eta.distance': 'Jarak',
    'eta.speed': 'Kecepatan',
    'eta.departure': 'Waktu Berangkat',
    'eta.eta': 'ETA',
    'eta.duration': 'Durasi',
    'eta.days': 'hari',
    'eta.hours': 'jam',
    'eta.minutes': 'menit',
    
    // Draft Survey
    'draft.title': 'Draft Survey',
    'draft.subtitle': 'Perhitungan Muatan',
    'draft.initial': 'Draft Awal',
    'draft.final': 'Draft Akhir',
    'draft.forward': 'Muka',
    'draft.midship': 'Tengah',
    'draft.aft': 'Belakang',
    'draft.port': 'Kiri',
    'draft.starboard': 'Kanan',
    'draft.parameters': 'Parameter',
    'draft.waterplaneArea': 'Luas Waterplane',
    'draft.coefficient': 'Koefisien',
    'draft.density': 'Densitas',
    'draft.initialDisp': 'Displacement Awal (MT) - Opsional',
    'draft.cargo': 'BERAT MUATAN',
    'draft.formula': 'Formula',
    'draft.hydrostatic': 'Tabel Hidrostatik',
    'draft.method': 'Metode',
    'draft.meanDraft': 'Mean Draft',
    'draft.tpc': 'TPC',
    'draft.lcf': 'LCF',
    'draft.mtc': 'MTC',
    'draft.displacement': 'Displacement',
    'draft.dwt': 'Deadweight',
    'draft.constant': 'Konstanta',
    'draft.lightShip': 'Light Ship',
    
    // Wind Calculator
    'wind.title': 'Kalkulator Angin',
    'wind.subtitle': 'True ↔ Apparent Wind',
    'wind.trueWind': 'Angin True',
    'wind.apparentWind': 'Angin Apparent',
    'wind.direction': 'Arah',
    'wind.speed': 'Kecepatan',
    'wind.vesselCourse': 'Course Kapal',
    'wind.vesselSpeed': 'Speed Kapal',
    'wind.result': 'Hasil',
    
    // Sextant
    'sextant.title': 'Sekstan',
    'sextant.subtitle': 'Koreksi Altitude',
    'sextant.observed': 'Altitude Teramati',
    'sextant.indexError': 'Error Index',
    'sextant.heightEye': 'Tinggi Mata',
    'sextant.result': 'Altitude True',
    'sextant.dip': 'Dip',
    'sextant.refraction': 'Refraksi',
    'sextant.parallax': 'Paralaks',
    'sextant.semidiameter': 'Semi-diameter',
    
    // COLREG
    'colreg.title': 'COLREG Reference',
    'colreg.subtitle': 'International Regulations',
    'colreg.rules': 'Peraturan',
    'colreg.lights': 'Lampu & Bentuk',
    'colreg.sounds': 'Suara',
    'colreg.flags': 'Bendera Sinyal',
    'colreg.disclaimer': 'Referensi cepat. Selalu rujuk COLREG resmi.',
    
    // Paint Calculator
    'paint.title': 'Kalkulator Cat',
    'paint.subtitle': 'Estimasi Konsumsi Cat',
    'paint.area': 'Luas Area',
    'paint.thickness': 'Ketebalan',
    'paint.efficiency': 'Efisiensi',
    'paint.loss': 'Kehilangan',
    'paint.result': 'Kebutuhan Cat',
    
    // Azimuth
    'azimuth.title': 'Azimut Matahari',
    'azimuth.subtitle': 'True Azimuth Calculator',
    'azimuth.date': 'Tanggal',
    'azimuth.time': 'Waktu',
    'azimuth.gmt': 'GMT',
    'azimuth.lha': 'LHA',
    'azimuth.declination': 'Deklinasi',
    'azimuth.amplitude': 'Amplitudo',
    'azimuth.result': 'Azimut True',
    
    // Compass Adjustment
    'compass.title': 'Kalibrasi Kompas',
    'compass.subtitle': 'Deviasi & Koreksi',
    'compass.heading': 'Heading',
    'compass.magnetic': 'Magnetic',
    'compass.deviation': 'Deviasi',
    'compass.deviationTable': 'Tabel Deviasi',
    'compass.recordMeasurement': 'Catat Pengukuran',
    'compass.measured': 'Terukur',
    'compass.calculated': 'Dihitung',
    'compass.difference': 'Selisih',
    'compass.addRow': 'Tambah Baris',
    'compass.removeRow': 'Hapus Baris',
    'compass.saveTable': 'Simpan Tabel',
    'compass.loadTable': 'Muat Tabel',
    'compass.clearTable': 'Bersihkan',
    
    // Star Finder
    'star.title': 'Pencari Bintang',
    'star.subtitle': 'Navigasi Astronomi',
    'star.date': 'Tanggal',
    'star.time': 'Waktu',
    'star.gmt': 'GMT',
    'star.lhaAries': 'LHA Aries',
    'star.selectedStars': 'Bintang Terpilih',
    'star.altitude': 'Altitude',
    'star.azimuth': 'Azimut',
    'star.magnitude': 'Magnitudo',
    
    // Logbook Reference
    'logbook.title': 'Referensi Logbook',
    'logbook.subtitle': 'Sea State, Weather & Clouds',
    'logbook.generatePDF': 'Generate PDF',
    'logbook.seaState': 'Keadaan Laut',
    'logbook.weather': 'Keadaan Cuaca',
    'logbook.clouds': 'Jenis Awan',
    'logbook.windForce': 'Angin (Beaufort)',
    'logbook.waveHeight': 'Tinggi Gelombang',
    'logbook.visibility': 'Jarak Pandang',
    
    // About
    'about.title': 'ASISTEN OFFICER',
    'about.subtitle': 'Marine Navigation Toolkit',
    'about.description': 'Toolkit navigasi maritim lengkap dengan perhitungan akurat dan modern. Dibuat untuk membantu officer di kapal.',
    'about.version': 'Versi 3.0 | WMM2025 | Offline',
    'about.coder': 'Developer: Mr. Wahid',
    
    // Toast messages
    'toast.calculationSuccess': 'Perhitungan berhasil',
    'toast.calculationError': 'Perhitungan gagal',
    'toast.positionAcquired': 'Posisi GPS berhasil diambil',
    'toast.positionError': 'Gagal mengambil posisi GPS',
    'toast.fieldsCleared': 'Semua kolom dibersihkan',
    'toast.exportSuccess': 'Export berhasil',
    'toast.saved': 'Data tersimpan',
    'toast.loaded': 'Data dimuat',
    'toast.languageChanged': 'Bahasa diubah',
    'toast.themeChanged': 'Tema diubah',
    
    // Errors
    'error.fillAllFields': 'Isi semua kolom',
    'error.invalidNumber': 'Masukkan angka yang valid',
    'error.invalidRange': 'Nilai di luar rentang yang valid',
    'error.negativeValue': 'Nilai tidak boleh negatif',
    'error.calculationFailed': 'Perhitungan gagal',
  },
  
  en: {
    // Menu items
    'menu.home': 'Home',
    'menu.magvar': 'Magnetic Variation',
    'menu.cpa': 'CPA / TCPA',
    'menu.eta': 'ETA Calculator',
    'menu.wind': 'Wind Calculator',
    'menu.sextant': 'Sextant',
    'menu.colreg': 'COLREG',
    'menu.draft': 'Draft Survey',
    'menu.paint': 'Paint Calculator',
    'menu.azimuth': 'True Azimuth',
    'menu.compass': 'Compass Adj',
    'menu.star': 'Star Finder',
    'menu.logbook': 'Logbook Ref',
    
    // Common
    'common.calculate': 'CALCULATE',
    'common.clear': 'CLEAR',
    'common.save': 'SAVE',
    'common.cancel': 'CANCEL',
    'common.close': 'CLOSE',
    'common.about': 'About',
    'common.settings': 'Settings',
    'common.language': 'Language',
    'common.export': 'EXPORT',
    'common.history': 'History',
    'common.degrees': 'degrees',
    'common.minutes': 'minutes',
    'common.knots': 'knots',
    'common.nm': 'NM',
    'common.meters': 'm',
    'common.tons': 'MT',
    
    // Home
    'home.title': 'MARINE NAVIGATION',
    'home.subtitle': 'Integrated Officer Assistance Toolkit',
    'home.version': 'Version',
    
    // Magnetic Variation
    'magvar.title': 'Magnetic Variation',
    'magvar.subtitle': 'WMM2025 - NOAA Compliant',
    'magvar.latitude': 'Latitude',
    'magvar.longitude': 'Longitude',
    'magvar.dateTime': 'Date & Time',
    'magvar.getPosition': 'Get GPS Position',
    'magvar.setNow': 'Set to Now',
    'magvar.headingConversion': 'Heading Conversion',
    'magvar.trueToCompass': 'True → Compass',
    'magvar.compassToTrue': 'Compass → True',
    'magvar.trueHeading': 'True Heading',
    'magvar.compassHeading': 'Compass Heading',
    'magvar.result': 'Magnetic Variation',
    'magvar.annualChange': 'Annual Change',
    'magvar.compassError': 'Compass Error',
    'magvar.epoch': 'WMM2025 Epoch',
    'magvar.calculatedHeading': 'Converted Heading',
    
    // CPA/TCPA
    'cpa.title': 'CPA / TCPA',
    'cpa.subtitle': 'Closest Point of Approach',
    'cpa.ownVessel': 'Own Vessel',
    'cpa.targetVessel': 'Target Vessel',
    'cpa.range': 'Range',
    'cpa.bearing': 'Bearing',
    'cpa.course': 'Course',
    'cpa.speed': 'Speed',
    'cpa.cpa': 'CPA',
    'cpa.tcpa': 'TCPA',
    'cpa.status': 'Status',
    'cpa.safe': 'SAFE',
    'cpa.caution': 'CAUTION',
    'cpa.danger': 'DANGER',
    'cpa.passed': 'PASSED',
    'cpa.cpaDistance': 'CPA Distance',
    'cpa.tcpaTime': 'Time to CPA',
    'cpa.cpaBearing': 'CPA Bearing',
    
    // ETA
    'eta.title': 'ETA Calculator',
    'eta.subtitle': 'Estimated Time of Arrival',
    'eta.distance': 'Distance',
    'eta.speed': 'Speed',
    'eta.departure': 'Departure Time',
    'eta.eta': 'ETA',
    'eta.duration': 'Duration',
    'eta.days': 'days',
    'eta.hours': 'hours',
    'eta.minutes': 'minutes',
    
    // Draft Survey
    'draft.title': 'Draft Survey',
    'draft.subtitle': 'Cargo Calculation',
    'draft.initial': 'Initial Draft',
    'draft.final': 'Final Draft',
    'draft.forward': 'Forward',
    'draft.midship': 'Midship',
    'draft.aft': 'Aft',
    'draft.port': 'Port',
    'draft.starboard': 'Stbd',
    'draft.parameters': 'Parameters',
    'draft.waterplaneArea': 'Waterplane Area',
    'draft.coefficient': 'Coefficient',
    'draft.density': 'Density',
    'draft.initialDisp': 'Initial Displacement (MT) - Optional',
    'draft.cargo': 'CARGO WEIGHT',
    'draft.formula': 'Formula',
    'draft.hydrostatic': 'Hydrostatic Table',
    'draft.method': 'Method',
    'draft.meanDraft': 'Mean Draft',
    'draft.tpc': 'TPC',
    'draft.lcf': 'LCF',
    'draft.mtc': 'MTC',
    'draft.displacement': 'Displacement',
    'draft.dwt': 'Deadweight',
    'draft.constant': 'Constant',
    'draft.lightShip': 'Light Ship',
    
    // Wind Calculator
    'wind.title': 'Wind Calculator',
    'wind.subtitle': 'True ↔ Apparent Wind',
    'wind.trueWind': 'True Wind',
    'wind.apparentWind': 'Apparent Wind',
    'wind.direction': 'Direction',
    'wind.speed': 'Speed',
    'wind.vesselCourse': 'Vessel Course',
    'wind.vesselSpeed': 'Vessel Speed',
    'wind.result': 'Result',
    
    // Sextant
    'sextant.title': 'Sextant',
    'sextant.subtitle': 'Altitude Corrections',
    'sextant.observed': 'Observed Altitude',
    'sextant.indexError': 'Index Error',
    'sextant.heightEye': 'Height of Eye',
    'sextant.result': 'True Altitude',
    'sextant.dip': 'Dip',
    'sextant.refraction': 'Refraction',
    'sextant.parallax': 'Parallax',
    'sextant.semidiameter': 'Semi-diameter',
    
    // COLREG
    'colreg.title': 'COLREG Reference',
    'colreg.subtitle': 'International Regulations',
    'colreg.rules': 'Rules',
    'colreg.lights': 'Lights & Shapes',
    'colreg.sounds': 'Sounds',
    'colreg.flags': 'Signal Flags',
    'colreg.disclaimer': 'Quick reference only. Always refer to official COLREG.',
    
    // Paint Calculator
    'paint.title': 'Paint Calculator',
    'paint.subtitle': 'Paint Consumption Estimation',
    'paint.area': 'Area',
    'paint.thickness': 'Thickness',
    'paint.efficiency': 'Efficiency',
    'paint.loss': 'Loss Factor',
    'paint.result': 'Paint Required',
    
    // Azimuth
    'azimuth.title': 'True Azimuth',
    'azimuth.subtitle': 'Sun Azimuth Calculator',
    'azimuth.date': 'Date',
    'azimuth.time': 'Time',
    'azimuth.gmt': 'GMT',
    'azimuth.lha': 'LHA',
    'azimuth.declination': 'Declination',
    'azimuth.amplitude': 'Amplitude',
    'azimuth.result': 'True Azimuth',
    
    // Compass Adjustment
    'compass.title': 'Compass Adjustment',
    'compass.subtitle': 'Deviation & Correction',
    'compass.heading': 'Heading',
    'compass.magnetic': 'Magnetic',
    'compass.deviation': 'Deviation',
    'compass.deviationTable': 'Deviation Table',
    'compass.recordMeasurement': 'Record Measurement',
    'compass.measured': 'Measured',
    'compass.calculated': 'Calculated',
    'compass.difference': 'Difference',
    'compass.addRow': 'Add Row',
    'compass.removeRow': 'Remove Row',
    'compass.saveTable': 'Save Table',
    'compass.loadTable': 'Load Table',
    'compass.clearTable': 'Clear',
    
    // Star Finder
    'star.title': 'Star Finder',
    'star.subtitle': 'Celestial Navigation',
    'star.date': 'Date',
    'star.time': 'Time',
    'star.gmt': 'GMT',
    'star.lhaAries': 'LHA Aries',
    'star.selectedStars': 'Selected Stars',
    'star.altitude': 'Altitude',
    'star.azimuth': 'Azimuth',
    'star.magnitude': 'Magnitude',
    
    // Logbook Reference
    'logbook.title': 'Logbook Reference',
    'logbook.subtitle': 'Sea State, Weather & Clouds',
    'logbook.generatePDF': 'Generate PDF',
    'logbook.seaState': 'Sea State',
    'logbook.weather': 'Weather',
    'logbook.clouds': 'Cloud Types',
    'logbook.windForce': 'Wind (Beaufort)',
    'logbook.waveHeight': 'Wave Height',
    'logbook.visibility': 'Visibility',
    
    // About
    'about.title': 'ASISTEN OFFICER',
    'about.subtitle': 'Marine Navigation Toolkit',
    'about.description': 'Complete maritime navigation toolkit with accurate calculations. Designed to assist officers on board.',
    'about.version': 'Version 3.0 | WMM2025 | Offline',
    'about.coder': 'Developer: Mr. Wahid',
    
    // Toast messages
    'toast.calculationSuccess': 'Calculation successful',
    'toast.calculationError': 'Calculation failed',
    'toast.positionAcquired': 'GPS position acquired',
    'toast.positionError': 'Failed to get GPS position',
    'toast.fieldsCleared': 'All fields cleared',
    'toast.exportSuccess': 'Export successful',
    'toast.saved': 'Data saved',
    'toast.loaded': 'Data loaded',
    'toast.languageChanged': 'Language changed',
    'toast.themeChanged': 'Theme changed',
    
    // Errors
    'error.fillAllFields': 'Please fill all fields',
    'error.invalidNumber': 'Please enter a valid number',
    'error.invalidRange': 'Value out of valid range',
    'error.negativeValue': 'Value cannot be negative',
    'error.calculationFailed': 'Calculation failed',
  },
  
  zh: {
    // Menu items
    'menu.home': '首页',
    'menu.magvar': '磁差',
    'menu.cpa': 'CPA / TCPA',
    'menu.eta': 'ETA计算器',
    'menu.wind': '风力计算器',
    'menu.sextant': '六分仪',
    'menu.colreg': 'COLREG',
    'menu.draft': '吃水测量',
    'menu.paint': '油漆计算器',
    'menu.azimuth': '真方位',
    'menu.compass': '罗盘校准',
    'menu.star': '星图',
    'menu.logbook': '日志参考',
    
    // Common
    'common.calculate': '计算',
    'common.clear': '清除',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.about': '关于',
    'common.settings': '设置',
    'common.language': '语言',
    'common.export': '导出',
    'common.history': '历史',
    'common.degrees': '度',
    'common.minutes': '分',
    'common.knots': '节',
    'common.nm': '海里',
    'common.meters': '米',
    'common.tons': '吨',
    
    // Home
    'home.title': '航海导航',
    'home.subtitle': '综合驾驶员辅助工具包',
    'home.version': '版本',
    
    // Magnetic Variation
    'magvar.title': '磁差',
    'magvar.subtitle': 'WMM2025 - NOAA标准',
    'magvar.latitude': '纬度',
    'magvar.longitude': '经度',
    'magvar.dateTime': '日期和时间',
    'magvar.getPosition': '获取GPS位置',
    'magvar.setNow': '设为现在',
    'magvar.headingConversion': '航向转换',
    'magvar.trueToCompass': '真航向 → 罗盘',
    'magvar.compassToTrue': '罗盘 → 真航向',
    'magvar.trueHeading': '真航向',
    'magvar.compassHeading': '罗盘航向',
    'magvar.result': '磁差',
    'magvar.annualChange': '年变化',
    'magvar.compassError': '罗盘误差',
    'magvar.epoch': 'WMM2025历元',
    'magvar.calculatedHeading': '转换后的航向',
    
    // CPA/TCPA
    'cpa.title': 'CPA / TCPA',
    'cpa.subtitle': '最近会遇距离',
    'cpa.ownVessel': '本船',
    'cpa.targetVessel': '目标船',
    'cpa.range': '距离',
    'cpa.bearing': '方位',
    'cpa.course': '航向',
    'cpa.speed': '速度',
    'cpa.cpa': 'CPA',
    'cpa.tcpa': 'TCPA',
    'cpa.status': '状态',
    'cpa.safe': '安全',
    'cpa.caution': '注意',
    'cpa.danger': '危险',
    'cpa.passed': '已通过',
    'cpa.cpaDistance': 'CPA距离',
    'cpa.tcpaTime': '到CPA时间',
    'cpa.cpaBearing': 'CPA方位',
    
    // ETA
    'eta.title': 'ETA计算器',
    'eta.subtitle': '预计到达时间',
    'eta.distance': '距离',
    'eta.speed': '速度',
    'eta.departure': '出发时间',
    'eta.eta': 'ETA',
    'eta.duration': '持续时间',
    'eta.days': '天',
    'eta.hours': '小时',
    'eta.minutes': '分钟',
    
    // Draft Survey
    'draft.title': '吃水测量',
    'draft.subtitle': '货物计算',
    'draft.initial': '初始吃水',
    'draft.final': '最终吃水',
    'draft.forward': '前',
    'draft.midship': '中',
    'draft.aft': '后',
    'draft.port': '左舷',
    'draft.starboard': '右舷',
    'draft.parameters': '参数',
    'draft.waterplaneArea': '水线面面积',
    'draft.coefficient': '系数',
    'draft.density': '密度',
    'draft.initialDisp': '初始排水量 (MT) - 可选',
    'draft.cargo': '货物重量',
    'draft.formula': '公式',
    'draft.hydrostatic': '静水力表',
    'draft.method': '方法',
    'draft.meanDraft': '平均吃水',
    'draft.tpc': 'TPC',
    'draft.lcf': 'LCF',
    'draft.mtc': 'MTC',
    'draft.displacement': '排水量',
    'draft.dwt': '载重吨',
    'draft.constant': '常数',
    'draft.lightShip': '空船重量',
    
    // Wind Calculator
    'wind.title': '风力计算器',
    'wind.subtitle': '真风 ↔ 视风',
    'wind.trueWind': '真风',
    'wind.apparentWind': '视风',
    'wind.direction': '方向',
    'wind.speed': '速度',
    'wind.vesselCourse': '船舶航向',
    'wind.vesselSpeed': '船舶速度',
    'wind.result': '结果',
    
    // Sextant
    'sextant.title': '六分仪',
    'sextant.subtitle': '高度修正',
    'sextant.observed': '观测高度',
    'sextant.indexError': '指标差',
    'sextant.heightEye': '眼高',
    'sextant.result': '真高度',
    'sextant.dip': '俯角',
    'sextant.refraction': '折射',
    'sextant.parallax': '视差',
    'sextant.semidiameter': '半直径',
    
    // COLREG
    'colreg.title': 'COLREG参考',
    'colreg.subtitle': '国际规则',
    'colreg.rules': '规则',
    'colreg.lights': '灯光和形状',
    'colreg.sounds': '声音',
    'colreg.flags': '信号旗',
    'colreg.disclaimer': '仅供参考。请参阅官方COLREG。',
    
    // Paint Calculator
    'paint.title': '油漆计算器',
    'paint.subtitle': '油漆消耗估算',
    'paint.area': '面积',
    'paint.thickness': '厚度',
    'paint.efficiency': '效率',
    'paint.loss': '损耗系数',
    'paint.result': '所需油漆',
    
    // Azimuth
    'azimuth.title': '真方位',
    'azimuth.subtitle': '太阳方位计算器',
    'azimuth.date': '日期',
    'azimuth.time': '时间',
    'azimuth.gmt': 'GMT',
    'azimuth.lha': 'LHA',
    'azimuth.declination': '赤纬',
    'azimuth.amplitude': '振幅',
    'azimuth.result': '真方位',
    
    // Compass Adjustment
    'compass.title': '罗盘校准',
    'compass.subtitle': '偏差和修正',
    'compass.heading': '航向',
    'compass.magnetic': '磁航向',
    'compass.deviation': '偏差',
    'compass.deviationTable': '偏差表',
    'compass.recordMeasurement': '记录测量',
    'compass.measured': '测量值',
    'compass.calculated': '计算值',
    'compass.difference': '差值',
    'compass.addRow': '添加行',
    'compass.removeRow': '删除行',
    'compass.saveTable': '保存表格',
    'compass.loadTable': '加载表格',
    'compass.clearTable': '清除',
    
    // Star Finder
    'star.title': '星图',
    'star.subtitle': '天文导航',
    'star.date': '日期',
    'star.time': '时间',
    'star.gmt': 'GMT',
    'star.lhaAries': 'LHA白羊座',
    'star.selectedStars': '选定星体',
    'star.altitude': '高度',
    'star.azimuth': '方位',
    'star.magnitude': '星等',
    
    // Logbook Reference
    'logbook.title': '日志参考',
    'logbook.subtitle': '海况、天气和云',
    'logbook.generatePDF': '生成PDF',
    'logbook.seaState': '海况',
    'logbook.weather': '天气',
    'logbook.clouds': '云类型',
    'logbook.windForce': '风力(蒲福)',
    'logbook.waveHeight': '波高',
    'logbook.visibility': '能见度',
    
    // About
    'about.title': 'ASISTEN OFFICER',
    'about.subtitle': '航海导航工具包',
    'about.description': '完整的航海导航工具包，具有准确和现代的计算功能。',
    'about.version': '版本 3.0 | WMM2025 | 离线',
    'about.coder': '开发者: Mr. Wahid',
    
    // Toast messages
    'toast.calculationSuccess': '计算成功',
    'toast.calculationError': '计算失败',
    'toast.positionAcquired': 'GPS位置已获取',
    'toast.positionError': '获取GPS位置失败',
    'toast.fieldsCleared': '所有字段已清除',
    'toast.exportSuccess': '导出成功',
    'toast.saved': '数据已保存',
    'toast.loaded': '数据已加载',
    'toast.languageChanged': '语言已更改',
    'toast.themeChanged': '主题已更改',
    
    // Errors
    'error.fillAllFields': '请填写所有字段',
    'error.invalidNumber': '请输入有效数字',
    'error.invalidRange': '值超出有效范围',
    'error.negativeValue': '值不能为负数',
    'error.calculationFailed': '计算失败',
  },
};

export function t(key: string, lang: Language): string {
  return translations[lang][key] || key;
}
