import { useCallback } from 'react';

export type ExportFormat = 'csv' | 'json' | 'pdf';

interface ExportOptions {
  filename?: string;
  timestamp?: boolean;
}

export function useExport() {
  const downloadFile = useCallback((content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, []);

  const exportToJSON = useCallback((data: unknown, options: ExportOptions = {}) => {
    const { filename = 'export', timestamp = true } = options;
    const timestampStr = timestamp ? `_${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}` : '';
    const fullFilename = `${filename}${timestampStr}.json`;
    
    const jsonContent = JSON.stringify(data, null, 2);
    downloadFile(jsonContent, fullFilename, 'application/json');
  }, [downloadFile]);

  const exportToCSV = useCallback((data: unknown, options: ExportOptions = {}) => {
    const { filename = 'export', timestamp = true } = options;
    const timestampStr = timestamp ? `_${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}` : '';
    const fullFilename = `${filename}${timestampStr}.csv`;

    if (!Array.isArray(data) || data.length === 0) return;

    const dataArray = data as Array<Record<string, unknown>>;
    const headers = Object.keys(dataArray[0]);
    const csvRows = [
      headers.join(','),
      ...dataArray.map(row => 
        headers.map(header => {
          const value = row[header];
          if (value === null || value === undefined) return '';
          const stringValue = String(value);
          if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
            return `"${stringValue.replace(/"/g, '""')}"`;
          }
          return stringValue;
        }).join(',')
      )
    ];

    downloadFile(csvRows.join('\n'), fullFilename, 'text/csv');
  }, [downloadFile]);

  const generatePDFContent = useCallback((title: string, content: string[][]): string => {
    const rows = content.map(row => 
      `<tr>${row.map(cell => `<td style="padding: 8px; border: 1px solid #ddd;">${cell}</td>`).join('')}</tr>`
    ).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #333; border-bottom: 2px solid #00eaff; padding-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #00eaff; color: white; padding: 10px; text-align: left; }
    td { border: 1px solid #ddd; }
    .footer { margin-top: 30px; font-size: 12px; color: #666; text-align: center; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p>Generated: ${new Date().toLocaleString()}</p>
  <table>
    ${rows}
  </table>
  <div class="footer">Generated by Officer Assistance App</div>
</body>
</html>`;
  }, []);

  return {
    exportToJSON,
    exportToCSV,
    generatePDFContent,
    downloadFile
  };
}
